root: true
extends:
- actano
- plugin:import/typescript
- plugin:mdx/recommended

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'

rules:
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
      mdx: never
  import/no-extraneous-dependencies:
  - error
  - devDependencies:
    - 'storybook/**/*.js'
    - 'storybook/**/*.jsx'
    - 'test/**/*.js'
    - 'test/**/*.jsx'
    - 'storybook/**/*.ts'
    - 'storybook/**/*.tsx'
    - 'storybook/**/*.mdx'
    - 'test/**/*.ts'
    - 'test/**/*.tsx'
  '@typescript-eslint/no-unused-vars': error
  no-unused-vars: off
  no-return-await: off
  import/prefer-default-export: off
  react/jsx-filename-extension:
    - 2
    - extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
        - '.mdx'

overrides:
  - files:
      - 'storybook/**/*.stories.mdx'
    parser: 'eslint-mdx'
    rules:
      react/jsx-indent: 'off'
      react/react-in-jsx-scope: 'off'
      max-len: 'off'
  - files:
      - 'test/**/*.js'
      - 'test/**/*.jsx'
      - 'test/**/*.ts'
      - 'test/**/*.tsx'
    env:
      mocha: true
    rules:
      no-unused-expressions: 'off'
      'mdx/no-unused-expressions': 'off'
    settings:
      import/core-modules:
        - chai
        - enzyme
        - sinon
  - files:
      - '**/*.ts'
      - '**/*.tsx'
    rules:
      no-undef: off
      react/prop-types: off
